### ISSUE TITLE
Keeping too many months

### ISSUE THREAD

**Issue by xombiemp** [stiang/ec2-purge-snapshots#2]
Thank you very much for this great script.  I'm having a small problem with it though;  it's keeping more months than I specified.  Here is the command and output to illustrate what I'm talking about:

[ec2-user@ip-10-0-0-39 ~]$ ec2-purge-snapshots --url http://ec2.us-west-1.amazonaws.com --hours 24 --days 3 --weeks 2 --months 1 --volumes vol-e168f385
---- VOLUME vol-e168f385 (34 snapshots) ---
[vol-e168f385]   Keeping  snap-59c6d33d: 2012-05-27T00:40:04.000Z, 96 days old - keeping it for the month of 2012-05
[vol-e168f385]   Keeping  snap-921bdbf5: 2012-06-03T00:40:04.000Z, 89 days old - keeping it for the month of 2012-06
[vol-e168f385]   Keeping  snap-7fa14f19: 2012-07-01T00:40:04.000Z, 61 days old - keeping it for the month of 2012-07
[vol-e168f385]   Keeping  snap-b7ee14ce: 2012-08-05T00:40:04.000Z, 26 days old - keeping it for the month of 2012-08
[vol-e168f385]   Keeping  snap-02bb412e: 2012-08-19T00:40:04.000Z, 12 days old - keeping it for the week of 2012-08-19
[vol-e168f385]   Keeping  snap-c177abed: 2012-08-26T00:40:04.000Z, 5 days old - keeping it for the week of 2012-08-26
[vol-e168f385]   Keeping  snap-66e1394a: 2012-08-28T00:40:04.000Z, 3 days old - keeping it for the day of 2012-08-28
[vol-e168f385]   Keeping  snap-0932e825: 2012-08-29T00:40:04.000Z, 2 days old - keeping it for the day of 2012-08-29
[vol-e168f385]   Keeping  snap-9864c0b4: 2012-08-30T00:40:04.000Z, 1 days old - keeping it for the day of 2012-08-30
[vol-e168f385]   Keeping  snap-a9ee4885: 2012-08-30T14:40:04.000Z, 24 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-78f85e54: 2012-08-30T15:40:04.000Z, 23 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-e0d573cc: 2012-08-30T16:40:04.000Z, 22 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-3ca10710: 2012-08-30T17:40:04.000Z, 21 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-cebf19e2: 2012-08-30T18:40:04.000Z, 20 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-e98b2dc5: 2012-08-30T19:40:04.000Z, 19 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-7b67c157: 2012-08-30T20:40:04.000Z, 18 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-7974d255: 2012-08-30T21:40:04.000Z, 17 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-8042e4ac: 2012-08-30T22:40:04.000Z, 16 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-1f51f733: 2012-08-30T23:40:04.000Z, 15 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-342a8c18: 2012-08-31T00:40:04.000Z, 14 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-4f07a163: 2012-08-31T01:40:04.000Z, 13 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-e712b4cb: 2012-08-31T02:40:05.000Z, 12 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-caed4ce6: 2012-08-31T03:40:05.000Z, 11 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-edc362c1: 2012-08-31T04:40:04.000Z, 10 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-dcd475f0: 2012-08-31T05:40:04.000Z, 9 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-17b0113b: 2012-08-31T06:40:03.000Z, 8 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-fc9130d0: 2012-08-31T07:40:05.000Z, 7 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-0970d125: 2012-08-31T08:40:05.000Z, 6 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-6e4ced42: 2012-08-31T09:40:04.000Z, 5 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-002d8c2c: 2012-08-31T10:40:04.000Z, 4 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-8d05a4a1: 2012-08-31T11:40:05.000Z, 3 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-091cbd25: 2012-08-31T12:40:04.000Z, 2 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-4dfb5b61: 2012-08-31T13:40:04.000Z, 1 hours old - less than or equal to the 24-hour threshold
[vol-e168f385]   Keeping  snap-b4cc6c98: 2012-08-31T14:40:03.000Z, 0 hours old - less than or equal to the 24-hour threshold

SUMMARY:

vol-e168f385:
  deleted: 0
  kept:    34

You can see that in the command I specified 1 month, but in the output it's keeping 4 monthly snapshots.  I would expect it to get rid of the last 3 snapshots since it's only supposed to keep 1 monthly.  I have tried to find the bug, but have not had any luck.  Can you take a look at it and see if you can figure out why this is happening?

**Comment by stiang** [comment]
Hmm, no, that does not look right. Thanks for the report. 

I’m quite busy at the moment, but I’ll try to find some time to fix this in the next few weeks.

**Comment by xombiemp** [comment]
This was fixed with https://github.com/stiang/ec2-purge-snapshots/issues/3
